fluencelabs/nox

build.sbt
vm/src/test/scala/fluence/vm/WasmVmSpec.scala

Change Asmble dependency to [Fluence's fork](https://github.com/fluencelabs/asmble), as we need to tune it up.

Adding fork of Asmble

---

statemachine/src/main/scala/fluence/statemachine/tx/VmOperationInvoker.scala
vm/examples/counter/src/main/scala/fluence/vm/examples/CounterRunner.scala
vm/src/main/scala/fluence/vm/ModuleInstance.scala
vm/src/main/scala/fluence/vm/VmError.scala
vm/src/main/scala/fluence/vm/WasmVm.scala
vm/src/main/scala/fluence/vm/WasmVmImpl.scala
vm/src/main/scala/fluence/vm/package.scala
vm/src/test/scala/fluence/vm/ModuleInstanceSpec.scala
vm/src/test/scala/fluence/vm/WasmVmImplSpec.scala
vm/src/test/scala/fluence/vm/WasmVmSpec.scala

Allows type-safe working with produced errors. For example:
```
val vm: fluence.vm.WasmVm = ???
vm.invoke[IO](None, "fnName", Seq()).leftMap {
case InvalidArgError(message, cause) ⇒  ???
case NoSuchFnError(message, cause) ⇒  ???
case TrapError(message, cause) ⇒ ???
// case InternalVmError(message, cause) ⇒ ???
}
```
Compiler checks that all of possible error types will be handled. If some of error types will not be handled compiler produce warning like this:
```  
Warning:(103, 50) match may not be exhaustive.
It would fail on the following input: InternalVmError(_, _)
vm.invoke[IO](None, "fnName", Seq()).leftMap {
```
This mean that {@link InternalVmError} will not be handled.

Remake Vm errors hierarchy 

---

vm/examples/counter/Cargo.toml
vm/examples/counter/src/main/rust/lib.rs
vm/examples/sqldb/Cargo.toml
vm/examples/sqldb/src/main/rust/lib.rs

VM Rust examples are built as libraries now.

Vm examples refactoring

---

vm/src/main/scala/fluence/vm/AsmleWasmVm.scala
vm/src/main/scala/fluence/vm/ModuleInstance.scala
vm/src/test/resources/wast/bad-allocation-function.wast
vm/src/test/resources/wast/counter-copy.wast
vm/src/test/resources/wast/counter.wast
vm/src/test/resources/wast/mul.wast
vm/src/test/resources/wast/no-getMemory.wast
vm/src/test/resources/wast/simple-array-mutation.wast
vm/src/test/resources/wast/simple-array-returning.wast
vm/src/test/resources/wast/simple-string-passing.wast
vm/src/test/resources/wast/sum-copy.wast
vm/src/test/resources/wast/sum-with-trap.wast
vm/src/test/resources/wast/sum.wast
vm/src/test/scala/fluence/vm/WasmVmSpec.scala

Fix rust integration issues:
- added additional supplied parameter to deallocate method that represent size of freeing memory;
- added order(ByteOrder.LITTLE_ENDIAN) before int has beed read;
- fixed test when 2 module has function with equal name.

Fix rust integration issues

---

.gitignore
.travis.yml
cli/Cargo.lock
project/SbtCommons.scala

I'll revert `nightly-2019-01-08` back to just `nightly` after https://github.com/rust-lang/rust/issues/57488 is resolved

Hardcode safe nightly build

---

cli/src/command.rs

Sort args in reversed order instead of sorting and then reversing.

Simplify `with_ethereum_args`

---

node/src/test/scala/fluence/node/ControlRpcSpec.scala
statemachine/control/src/main/scala/fluence/statemachine/control/ControlServer.scala
statemachine/control/src/test/scala/fluence/statemachine/control/ControlServerSpec.scala
statemachine/src/main/scala/fluence/statemachine/ServerRunner.scala
statemachine/src/test/scala/fluence/statemachine/StatemachineIntegrationSpec.scala
vm/src/main/scala/fluence/vm/AsmbleWasmVm.scala
vm/src/main/scala/fluence/vm/WasmVm.scala
vm/src/main/scala/fluence/vm/wasm/module/MainWasmModule.scala

A temporary solution to let users configure their ethereum expectations via WASM bytecode: to set the flag, just export `expects_eth` method from the module.

`expectsEth` flag in `WasmVm`

---

effects/tendermint-rpc/src/test/scala/fluence/Eventually.scala
effects/tendermint-rpc/src/test/scala/fluence/Timed.scala
effects/tendermint-rpc/src/test/scala/fluence/effects/tendermint/rpc/WebsocketRpcSpec.scala
node/src/it/scala/fluence/node/MasterNodeIntegrationSpec.scala
node/src/it/scala/fluence/node/MasterNodeSpec.scala
node/src/test/scala/fluence/node/BlockUploadingSpec.scala
node/testkit/src/test/scala/fluence/node/BlockUploadingIntegrationSpec.scala
node/testkit/src/test/scala/fluence/node/PerBlockTxExecutorSpec.scala
node/testkit/src/test/scala/fluence/node/ResponseSubscriberSpec.scala
node/testkit/src/test/scala/fluence/node/WebsocketApiSpec.scala

Previously, `eventually` would hang if passed task hangs. Now it would stop with timeout exception after `maxWait` no matter what.
Also, now `eventually` would stop running task after specified `period`.

Add strict timeout to Eventually

---

Cargo.lock
client/rust-libp2p/src/client.rs
deploy/prometheus/prometheus.yml
node_client.mk
server/src/behaviour/bootstrapper.rs
server/src/behaviour/identify.rs
server/src/behaviour/server_behaviour.rs
server/src/bootstrapper/behaviour.rs
server/src/bootstrapper/event.rs
server/src/function/peers.rs
server/src/function/router.rs
server/src/function/services.rs
server/tests/run_multiple_nodes.rs
server/tests/utils/connected_client.rs
server/tests/utils/misc.rs

- `FunctionRouter::bootstrap` now just calls `find_closest(self.local_peer_id)` instead of full maintenance procedure
- Add bootstrap reconnect backoff
- Disable bootstrap reconnect via peer_id: it was producing InvalidPeerId errors, and served no purpose
- Add `PeerStatus::CheckedRoutable` for when we know peer must be routable, but there's no way to check that (maybe will delete PeerStatus::Routable in future)
- Add `context` to `send_to` to improve error messages (though it's a rather ad-hoc way, redesign needed there)
- Fixed `get_closest_peers`: now search uses `Qm...` peer ids instead of `12D...` peer ids.

Change bootstrap procedure & fix bugs in routing

---

client/rust-libp2p/src/behaviour.rs
client/rust-libp2p/src/client.rs
faas-api/src/lib.rs
faas-api/src/libp2p_protocol/upgrade.rs
server/src/function/router_behaviour.rs

Currently `ProtocolConfig::peer_id` is unused. It will be used in the following PR.

Protocol config

---

client/fluence-ipfs/src/lib.rs
client/rust-libp2p/src/client.rs
client/rust-libp2p/src/main.rs
client/rust-libp2p/tests/endurance.rs
faas-api/src/address.rs
faas-api/src/address_protocol.rs
faas-api/src/call.rs
server/src/bootstrapper/behaviour.rs
server/src/function/builtin_service.rs
server/src/function/execution.rs
server/src/function/peers.rs
server/src/function/router.rs
server/src/function/router_behaviour.rs
server/src/function/services.rs
server/tests/routing.rs
server/tests/run_multiple_nodes.rs
server/tests/utils/misc.rs

1. Local services are now addressed via `#`: `fluence:/peer/QmPeer#identify`
2. `/service` renamed to `/providers`: `fluence:/service/IPFS`
3. Services are now published to DHT by `#`. This means that calling 
```
FunctionCall {
target: fluence:/#provide
arguments: { service_id: IPFS },
reply_to: /peer/QmPeer/client/QmClient/signature/QmSig,
...
}
```
Will publish to DHT the following: `#IPFS -> [ /peer/QmPee/client/QmClient/signature/QmSig ]`
4. Same conversion happens when resolving providers through DHT. A request like
```
FunctionCall {
target: fluence:/providers/IPFS,
...
}
```
Will result in searching for `#IPFS` on DHT, and then forwarding call, using `#IPFS`:
```
target: fluence:/peer/QmPeer/client/QmClient#IPFS
```

Route by hashtag

---

Cargo.lock
server/Cargo.toml
server/src/faas/behaviour.rs
server/src/function/errors.rs
server/src/function/execution.rs
server/src/function/services.rs
server/tests/routing.rs
server/tests/utils/faas.rs

I don't like this solution, it's too fragile. 
Ideally, there should be an abstraction that manages its directories, and interprets `mapped_dirs` as relative paths to service directory. 
But for now, it should do.

Isolate mapped_dirs and preopened_files among faas instances

---

trust-graph/src/trust_graph.rs

Having `expect` with the message inside is better than having the message in comments and using `unwrap`

use expect instead of unwrap

---

.github/workflows/rust_audit.yml
Cargo.lock
aquamarine/src/vm_pool.rs
connection-pool/Cargo.toml
connection-pool/src/api.rs
connection-pool/src/behaviour.rs
connection-pool/src/connection_pool.rs
crates/ctrlc-adapter/Cargo.toml
crates/kademlia/src/behaviour.rs
crates/kademlia/src/lib.rs
crates/libp2p/Cargo.toml
crates/server-config/src/kademlia_config.rs
crates/test-utils/Cargo.toml
crates/test-utils/src/misc.rs
particle-closures/src/host_closures.rs
particle-node/src/behaviour/network.rs
particle-node/tests/echo_particle.rs
particle-node/tests/network_explore.rs
particle-protocol/Cargo.toml
particle-protocol/src/libp2p_protocol/upgrade.rs

Timeouts added to:
Connection Pool: 
- send, because libp2p can silently drop outbound messages
Kademlia:
- discover peer, because there's no guarantee that discovered peer will ever connect
I expect timeouts for all other methods to be already managed through libp2p.

Add timeouts to connection pool & kademlia

---

particle-closures/src/host_closures.rs
particle-node/tests/builtin.rs

Previously `("peer" "timestamp_ms")` execution failed with:
```
[2021-05-18T21:43:24.932946Z INFO  aquamarine::particle_executor] Executing particle 4d8cb775-3d73-4f42-84d4-fd2fd095a312
thread 'blocking-58' panicked at 'called `Result::unwrap()` on an `Err` value: Error("u128 is not supported", line: 0, column: 0)', /home/circleci/project/particle-closures/src/host_closures.rs:139:53
```

fix timestamp_ms execution problem, add test

---

crates/host-closure/src/args_error.rs
particle-closures/src/host_closures.rs
particle-node/tests/builtin.rs
particle-node/tests/network_explore.rs

`(op noop)` – always returns empty string (unit)
`(op array)` – accepts any number of arguments and wraps them in a single array
`(op concat)` – accepts any number of arrays and concatenates them
`(op identity)` – accepts at most 1 arguments and returns it; if no arguments, empty string (unit) is returned
```scala
Op.noop() -> ()
Op.array(args: any[]) -> any[]
Op.concat(args: any[][]) -> any[]
Op.identity(a: Option<any>) -> Option<any>
```

Add ops noop, concat, array; change op identity to return scalar

---

Cargo.lock
Cargo.toml
aquamarine/Cargo.toml
client/rust-libp2p/Cargo.toml
connection-pool/Cargo.toml
crates/kademlia/Cargo.toml
crates/kademlia/src/api.rs
crates/kademlia/src/behaviour.rs
crates/libp2p/Cargo.toml
crates/server-config/Cargo.toml
crates/test-utils/Cargo.toml
particle-closures/Cargo.toml
particle-closures/src/host_closures.rs
particle-node/Cargo.toml
particle-protocol/Cargo.toml

fixes #1113 
neighborhood now accepts third parameter: 
`count` - optional number, defaults to 20. If set, used as a limit to the number of returned nodes

Limit neighborhood nodes to K

---

deploy/Config.default.toml

There was a bug in Config.default.toml: service dirs were put to `/` instead of `/.fluence/v1`

Fix default services, stepper & certificate dirs

---

crates/created-swarm/src/swarm.rs
crates/server-config/src/listen_config.rs
crates/server-config/src/node_config.rs
crates/server-config/src/resolved_config.rs
deploy/Config.default.toml
deploy/compose.py
deploy/fluence.py
particle-node/src/main.rs
particle-node/src/node.rs
particle-node/tests/aqua_dht/aqua_dht.rs

On deploy, it become hard to actually get `server peer id` from logs. So I put that log earlier.

Log server peer id earlier

---

aquamarine/src/particle_data_store.rs
crates/fs-utils/src/lib.rs

1. It was using `remove_dir` on a file, now it uses `remove_file`
2. Now `remove_dir` and `remove_file` always ignore `NotFound` error

Particle Data Store: fix cleanup function

---

Cargo.lock
aquamarine/Cargo.toml
aquamarine/src/aqua_runtime.rs
aquamarine/src/config.rs
crates/created-swarm/src/swarm.rs
crates/libp2p/Cargo.toml
crates/local-vm/Cargo.toml
crates/local-vm/src/local_vm.rs
crates/particle-args/Cargo.toml
crates/server-config/Cargo.toml
crates/server-config/src/node_config.rs
crates/server-config/src/services_config.rs
crates/toy-vms/Cargo.toml
particle-builtins/Cargo.toml
particle-builtins/src/builtins.rs
particle-modules/Cargo.toml
particle-modules/src/error.rs
particle-modules/src/modules.rs
particle-node/Cargo.toml
particle-node/src/main.rs
particle-node/src/node.rs
particle-services/Cargo.toml
particle-services/src/app_services.rs

- bump fluence-app-service to 0.11.1
- bump avm-server to 0.12.0
- add aquavm_max_heap_size, module_max_heap_size and module_default_heap_size to node's config
- check max_heap_size overflow in `add_module`

specify heap size settings for modules; avm-server 0.12

---

README.md
crates/log-utils/src/lib.rs
particle-builtins/src/builtins.rs
particle-node/tests/script_storage.rs
script-storage/src/script_storage.rs

Also:
- Add debug logs to understand why failed scripts aren't removed
- Express `oneshot` logic explicitly with `executions` and `times` state variables

Scheduled scripts: derive particle_id from script_id

---

connection-pool/src/behaviour.rs

As @mxinden has suggested in https://github.com/libp2p/rust-libp2p/issues/2602#issuecomment-1107441110, it makes sense to log dial and listening errors. This way, we can know who causes errors like recent EOF-bug.

Log connection failures

---

particle-builtins/src/math.rs

[`checked_log`](https://doc.rust-lang.org/stable/std/primitive.i64.html#method.checked_log) method was renamed to `checked_ilog` in https://github.com/rust-lang/rust/pull/100332
`rust-ci` workflow uses nightly tool-chain so without this change tests would fail

Change `checked_log` to `checked_ilog`

---

.github/workflows/snapshot.yml

Do not run cargo nextest when building snapshot.
TODO:
warn on test failure
run cargo next as a parallel job

ci: Run cargo build instead of nextest

---

.github/snapshot/Dockerfile

Temporarily add registry to snapshot builtins. Needed now to run registry e2e tests.
Better solution is to use node-distro Dockerfile to build a snapshot. Will be done later.

ci: Add regitstry to snapshot

---

particle-services/Cargo.toml
particle-services/src/app_services.rs

Fix the problem that if we add to a service alias that already was given to another service, then after a restart, both services will have this alias.

Fix doubling aliases when adding an alias to a service

---

.github/snapshot/Dockerfile
.github/workflows/snapshot.yml

- set version in `Cargo.toml` so `fluence --version` displays something like `Fluence node 0.7.2-alpha.1-set-version-snapshot-463ee7f-138-1; AIR version 0.31.4`
- migrate `set-output` to new format to get read of warnings
- print instructions on how to run rust-peer snapshot to checks summary instead of comment

ci: Set snapshot version in Cargo.toml

---

crates/spell-event-bus/src/bus.rs
particle-node/src/node.rs
particle-node/tests/spells.rs
sorcerer/src/lib.rs
sorcerer/src/sorcerer.rs
sorcerer/src/spells.rs
sorcerer/src/utils.rs

This can be considered a fast implementation because there are some parts I don't like:
1. Event bus API is available before it can be used because of all API methods, despite being async, wait for the result from the event bus. The result is just a unit that states that the command was processed.
2. Rescheduling spell happens in the `start` methods, merely before the sorcerer starts. Doesn't look good. 
Event bus API is used in sorcerer, so we can't just create it on event-bus start and then pass it to `sorcerer.start(api)`.
So solutions I see are:
1. Start event bus before sorcerer creation in `Node::new`. Doesn't look like a good place for spawning processes, though. 
2. Make rescheduling spells an explicit separate step and call it after the event bus and sorcerer start (somehow …

Add spell rescheduling after restart

---

particle-builtins/src/builtins.rs
particle-node/tests/spells.rs
particle-services/src/app_services.rs
sorcerer/src/spells.rs

Now I see only a hack way to implement spells removal. And I think we need to enable it.
We need to somehow detect whether the given id is a spell, but now I don't see how we can share `spell_storage` info with `builtins` to do it the right way.

Enable spell removal api

---

Cargo.lock
crates/spell-event-bus/Cargo.toml
crates/spell-event-bus/src/api.rs
crates/spell-event-bus/src/bus.rs
particle-node/src/node.rs
particle-node/tests/spells.rs
sorcerer/src/script_executor.rs
sorcerer/src/sorcerer.rs

Trigger info is stored in spell KV storage by the "trigger_mailbox" key and can be obtained via `spell.list_pop_string`
The next code should be put in aqua-lib:
```
data TimerTrigger:
timestamp: u64
data PeerTrigger:
peer_id: PeerId
connected: boolean
data TriggerEvent:
timer: ?TimerTrigger
peer: ?PeerTrigger
service TriggerEventJson:
parse(s: string) -> TriggerEvent
func get_trigger() -> TriggerEvent:
s <- Spell.list_pop_string("trigger_mailbox)
trigger <- TriggerEventJson.parse(s)
<- trigger
```

feat(spells): store trigger info in spell mailbox [NET-225]

---

crates/particle-node-tests/tests/spells.rs
sorcerer/src/spells.rs

- spell's `getDataSrv` returns parsed json value, so there is no need to parse it manually
- `spell.install` now accepts any object as `init_data` (previously, it was accepting only stringified ones)
- spell's `response` accepts objects (previously, it was accepting only stringified ones)

feat(spells): do json manipulations internally

---

Cargo.lock
crates/json-utils/src/lib.rs
crates/libp2p/src/serde.rs
crates/log-utils/src/lib.rs
crates/particle-args/src/args_error.rs
crates/particle-node-tests/tests/builtin.rs
crates/particle-node-tests/tests/script_storage.rs
crates/particle-node-tests/tests/spells.rs
particle-builtins/src/builtins.rs
particle-builtins/src/json.rs

`json.obj` and `json.puts` are basically varargs, which gives flexibility, but is impossible to express in well-typed Aqua.
`json.obj` allows to build JSON object from an array of `(string, json)` pairs.

feat(builtins): json.obj_pairs, json.puts_pairs to build JSON objects from array of pairs

---

crates/spell-event-bus/src/config.rs
sorcerer/src/sorcerer.rs

Right now _all_ spells will be rerun after the node restart, even the ones that ended before restarting. 
So the new rule is:  _the spell won't be restarted if in its trigger config `end_at <= now` or it's a one-shot spell that started in the past_.
Not sure about the following events:
1. The spell is a one-shot that should be run immediately or was running, but the node was restarted during the process.
2. The periodic spell with `end_at` was added, then the node was shut down until `end_at`, so the spell was never executed.
These events don't seem to be very relevant though.

fix(spells): do not run spells with passed (ended) Clock trigger

---

Cargo.lock
aquamarine/Cargo.toml
aquamarine/src/plumber.rs
crates/key-manager/src/key_manager.rs
crates/particle-node-tests/tests/builtin.rs
crates/particle-node-tests/tests/spells.rs
crates/peer-metrics/src/services_metrics/external.rs
particle-builtins/src/builtins.rs
particle-node/src/node.rs
particle-services/src/app_service.rs
particle-services/src/app_services.rs
particle-services/src/persistence.rs
sorcerer/src/spells.rs

- decider can be deployed to the root scope with management keypair
- decider alias will be resolvable in the root scope

feat(workers): allow to deploy decider to root scope, fix aliasing

---

particle-modules/src/error.rs
particle-services/src/app_service.rs
particle-services/src/app_services.rs
particle-services/src/error.rs
particle-services/src/lib.rs
particle-services/src/persistence.rs

\+ a little bit of refactoring

fix: bug with repeated alias for service [NET-434]

---

Cargo.lock
particle-builtins/src/builtins.rs
particle-builtins/src/identify.rs
particle-node/Cargo.toml
particle-node/src/builtins.rs
particle-node/src/lib.rs
particle-node/src/node.rs
sorcerer/src/sorcerer.rs
spell-storage/src/storage.rs

Extend `Peer.identify`
* add list of `allowed_binaries`
* add `spell_version`
Looks like this
```json
{
"air_version": "0.38.0",
"allowed_binaries": [
"/usr/bin/ipfs",
"/usr/bin/curl"
],
"external_addresses": [],
"node_version": "0.9.1",
"spell_version": "0.5.6"
}
```
Spell version is determent as follows:
1. If it's loaded from crate, the crate version is in use.
2. If it's loaded from disk, version is in the format `wasm hashes <hash1[..8]> <hash2[..8]>` with first 8 symbols of each hash.
To do this, I needed to move `Peer.identify` implementation from builtins to the sorcerer. Can't say I like it very much, but it works.

feat: extend peer identify with spell service version and allowed mounted binaries list [fixes NET-429 NET-381]

---

crates/peer-metrics/src/info.rs
crates/peer-metrics/src/lib.rs
particle-node/src/node.rs

Add new `rust_peer_build_info` metric.
```
rust_peer_version_info{peer-version="0.9.1",air-version="0.38.0",spell-version="0.5.6"} 1
```
These versions are the same as in `Peer.identify`: `peer-version` is from `CARGO_PKG_VERSION`, `air-version` is `air_interpreter_wasm::VERSION`.
~~I think, atm it's enough to add only basic versions. Suggest to extend it when we feel that we need it.~~
UPD: ~~I'll add spell version and builtins versions.~~
UPD: added spell_version

feat(metrics): add rust-peer version info in prometheus metrics [fixes NET-422]

---

connection-pool/src/behaviour.rs
crates/peer-metrics/src/connection_pool.rs
crates/peer-metrics/src/connectivity.rs
crates/peer-metrics/src/dispatcher.rs
crates/peer-metrics/src/lib.rs
particle-node/src/connectivity.rs
particle-node/src/dispatcher.rs

Added a separate metrics collection for a number of partcile metrics:
* received_particles
* particle_sizes
* particle_send_success
* particle_send_failure
* expired_particles
Each of the metrics above now has a label with "Common" for every common particle and "Spell" for `spell_` prefixed particles.
I chose this metrics because it made sense to me, but I'm open to discussion.

feat: collect metrics for spell particles separately [fixes NET-439]

---

Cargo.lock
particle-services/src/app_services.rs

Forgot to fix collection of mem metrics on service creation.

fix(metrics): restrict metrics collection of aliased service on creation

---

crates/peer-metrics/src/services_metrics/external.rs
crates/peer-metrics/src/services_metrics/mod.rs
particle-services/src/app_services.rs

Add a new service type for spells and spells with aliases.
Extend some new metrics with labels:
* services_count
* creation_time_msec
* removal_time_msec
* creation_count
* removal_count
And add a __hack__ to detect that a service is a spell _fast_, without rechecking the blueprint cache on every call.
Need to design a non-hacky way to distinguish a service and a spell, I think. It will be needed not only for this metrics collection thing but also for rewriting the registry and other built-in services as spells.

feat: add service metrics for spells [fixes NET-441]

---

crates/created-swarm/src/swarm.rs
crates/server-config/src/defaults.rs
crates/server-config/src/dir_config.rs
crates/server-config/src/lib.rs
nox/src/node.rs

Builtins dir is unused, but is created on the Nox start.
It causes build to fail in nox-distro if `/builtins` is not chowned.

feat(builtins): remove builtins dir from configs

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/tests.yml
Cargo.lock
Cargo.toml
crates/nox-tests/tests/spells.rs

Spell Mailbox API has changed, and some tests should be updated
- depends on fluencelabs/spell#154

fix(spell): bump spell to 0.5.17 and fix tests

---

Cargo.lock
Cargo.toml
aquamarine/Cargo.toml
aquamarine/src/aquamarine.rs
aquamarine/src/health.rs
aquamarine/src/lib.rs
aquamarine/src/plumber.rs
aquamarine/src/vm_pool.rs
crates/health/Cargo.toml
crates/health/src/lib.rs
crates/server-config/src/defaults.rs
crates/server-config/src/network_config.rs
crates/server-config/src/node_config.rs
nox/Cargo.toml
nox/src/behaviour/network.rs
nox/src/connectivity.rs
nox/src/health.rs
nox/src/http.rs
nox/src/lib.rs
nox/src/node.rs
particle-builtins/Cargo.toml
particle-builtins/src/builtins.rs
particle-services/Cargo.toml
particle-services/src/app_services.rs
particle-services/src/health.rs
particle-services/src/lib.rs

Added health check HTTP endpoint
For now it is not possible to understand the status of node, it can be fully or partially broken. Health check allows to define critical checks to determine a system status.
- Added a health check registry with stores all checkers.
- The HTTP status based on the [consul docs](https://developer.hashicorp.com/consul/docs/services/usage/checks#http-checks).
Also was fixed metric for bootstrap disconnected. it was applied for all disconnected events, not only bootstrap addresses.

feat(http): Added http healthcheck endpoint

---

crates/nox-tests/tests/spells.rs
sorcerer/src/script_executor.rs

Store only the last trigger event from nox (connection pool and timer trigger events) in spell KV by `trigger` key.
Previously, trigger events were stored in the Spell Mailbox, but it can be used by other spells and clients to pass data to the spell, and it became hard to distinguish trigger events from other events. We decided to store only the last trigger separately, so spell developers can easily find the event that triggered spell execution by adding `trigger` arg to spell signature:
```
import TriggerEvent from "@fluencelabs/spell/trigger.aqua"
func spell_main(trigger: TriggerEvent, init_arg1: string, ...):
...
```
- store nox trigger events in spell KV by `trigger` key
[Add any relevant screenshots or …

feat(spells): store last trigger by `trigger` key in KV [NET-511]

---

Cargo.toml
crates/server-config/src/args.rs
crates/server-config/src/resolved_config.rs

Renamed metric-port argument to http-port
Lost configuration update. Metrics port was renamed to more generic HTTP port

fix(config): fix http port argument

---

crates/nox-tests/tests/builtin.rs
particle-builtins/src/builtins.rs

Provide a non-throwing method to resolve alias.
We often call `Srv.resolve_alias` to check whether or not a service exists, but this method throws an error in the absence of this alias, which pollutes nox logs:
```
2023-08-19T00:07:09.186925Z  WARN tokio ThreadId(08) aquamarine::particle_functions: Failed host call "srv" "resolve_alias" "worker-spell" (36us 167ns): "Error: Service with alias 'worker-spell' is not found on worker '12D3KooWMXaLQfKpH6PnfcAjmnPsaz5gLMjZ6knmVN28THaYpd8v'\nNoSuchAlias(\"worker-spell\", PeerId(\"12D3KooWMXaLQfKpH6PnfcAjmnPsaz5gLMjZ6knmVN28THaYpd8v\"))" particle_id="spell_5c84196c-e598-460f-8965-128354d9f140_0"
```
Implement `Srv.resolve_alias_opt`:
```
service Srv:
resolve_alias_opt(alias: string) -> ?string
```

feat(builtins): add resolve_alias_opt [NET-528]

---

crates/nox-tests/tests/spells.rs
sorcerer/src/sorcerer.rs
sorcerer/src/worker_builins.rs

Provide a non-throwing method to get worker peer id.
We often call `Worker.get_peer_id` on decider spell to check whether or not a worker exists, but this method throws an error in the absence of a worker, which pollutes nox logs:
```
2023-08-16T17:34:28.579229Z  WARN tokio ThreadId(09) aquamarine::particle_functions: Failed host call "worker" "create" ["0x254fb741db88469b152d30f09396779d02cb7be6"] (146us 875ns): "Error: Worker for 0x254fb741db88469b152d30f09396779d02cb7be6 already exists\nWorkerAlreadyExists { deal_id: \"0x254fb741db88469b152d30f09396779d02cb7be6\" }" particle_id="spell_86b9e58f-0385-4247-a8a1-84e8ae546b58_1"
```
Implement Worker.get_worker_id:
```
service Worker:
get_worker_id(deal_id: ?string) -> ?PeerId
```
`Worker.get_peer_id` will be deprecated soon.

feat(workers): add Worker.get_worker_id [NET-523]

---

Cargo.lock
crates/server-config/src/node_config.rs
crates/system-services/Cargo.toml
crates/system-services/src/distro.rs

Allow to override decider ipfs multiaddr from ENV.
It's necessary to flexibly configure noxes and crucial for local testing setup.
- set decider ipfs multiaddr via `FLUENCE_ENV_DECIDER_IPFS_MULTIADDR
- show overridden values in logs
- bump aqua-ipfs to 0.5.20
- allow to reconfigure aqua-ipfs

feat(decider): allow to set ipfs multiaddr from env [fixes NET-544]

---

crates/server-config/src/resolved_config.rs
particle-protocol/src/libp2p_protocol/upgrade.rs

Fix protocol config configuration loading from env 
FLUENCE_PROTOCOL_CONFIG__UPGRADE_TIMEOUT doesn't work if another parameters from protocol config wasn't specified

fix: env configuration loading for protocol config

---

crates/created-swarm/src/lib.rs
crates/created-swarm/src/swarm.rs

IPFS and curl paths can differ in CI, so we need some way to override them. Also, it may be nice to control other configs also.  
Add the `override_system_services_config: Option<SystemServicesConfig>` field in `SwarmConfig`.
Requires importing `server-config` crate to get access to the definition and default values. 
Proposed use:
```rust
make_swarm_with_cfg(1, move |mut cfg| {
let mut services_cfg = SystemServicesConfig::default();
services_cfg.aqua_ipfs.ipfs_binary_path = "/new/path/to/ipfs".to_string()
cfg.override_system_services_config = Some(services_cfg);
cfg
}) 
```

fix(tests): Allow override system services config in tests [NET-576]

---

aquamarine/src/particle_functions.rs
aquamarine/src/plumber.rs
crates/peer-metrics/src/services_metrics/builtin.rs
crates/peer-metrics/src/services_metrics/external.rs
crates/peer-metrics/src/services_metrics/message.rs
crates/peer-metrics/src/services_metrics/mod.rs
particle-services/src/app_services.rs

- Report actor mailbox size and actor counts in every poll. Before this PR, it was only reported when there are `interpretation_stats`.
- Measure lock wait time separately from marine execution time in AppService
- Measure time it takes for service call execution to be scheduled on Blocking Pool in Actor
- Separate call execution time measurement from schedule wait time in Actor
Including queuing time from latency measurements skews measurements when system is saturated. In such form, measurement doesn't make much sense: it will obviously grow as more work arrives.
Instead, execution latency should be measured separately, to allow for applying eg Little's Law to estimate system's throughput  at given execution latencies.
Another benefit of that separation is that we get a clear picture of …

fix(metrics): measure call time and wait time separately

---

crates/server-config/src/args.rs
particle-builtins/src/builtins.rs

Add two new flags:
- `--wallet-key KEY`
- `--enable-system-services=LIST`
- `--enable-system-services=all` to enable all available services
- `--enable-system-services=service1,service2` to enable only services from the list
- `--enable-system-services=none` to disable all services (disabling now doesn't work, it will be introduce by some other task)
Also, make nox fail when a wallet key isn't set when decider is enabled. 
To be user-friendly
These flags are introduced via the existing mechanism of layer configs, so we don't have a lot of control here.

feat(nox): add new flags for system services [NET-547, NET-548]

---

.config/nextest.toml
crates/nox-tests/tests/boolean_test.rs
crates/nox-tests/tests/builtin.rs
crates/nox-tests/tests/echo_particle.rs
crates/nox-tests/tests/kademlia.rs
crates/nox-tests/tests/network/loop_topology.rs
crates/nox-tests/tests/network/network_explore.rs
crates/nox-tests/tests/tetraplets.rs
crates/nox-tests/tests/topology.rs

Run heavy (swarms >= 3) tests multithreaded, add `#[tokio::test(flavor = "multi_thread", worker_threads = 2)]`. Create only 1 swarm if no more is needed.
Some tests periodically fail in ci.

chore(tests): optimization + run heavy test multithreaded

---

.config/nextest.toml
aquamarine/src/particle_effects.rs
aquamarine/src/particle_executor.rs
aquamarine/src/plumber.rs
crates/peer-metrics/src/particle_executor.rs

Separate an AVM call time & interpretation time metrics.
For now, the interpretation time metric shows as the interpretation time +  disk IO time. We want to expose information without IO to clearly understand the AVM behavior.
interpretation_time becomes time from AVM metrics and shows only interpretation.
call_time is a previous interpretation_time.

fix(metrics): separate a avm call time & interpretation time metrics

---

Cargo.lock
crates/server-config/src/resolved_config.rs
nox/Cargo.toml
nox/src/layers.rs
nox/src/lib.rs
nox/src/main.rs

Added a sample rate to the otlp config. 
For now, we don't have a sampler configuration. To reduce pressure on the tracing collector I have added an additional property into the configuration.
[https://linear.app/fluence/issue/NET-631/improve-otlp-tracing-config](https://linear.app/fluence/issue/NET-631/improve-otlp-tracing-config)
- Added a config for sampler
- Env filter becomes the separate layer to reduce the event count for the tracing subscriber
- Added peer_id to the tracing layer for better understanding in the tracing viewer.
- Added stdout tracing output for the devs

feat(tracing): add sample rate + filtering

---

crates/key-manager/src/key_manager.rs
crates/key-manager/src/lib.rs
crates/nox-tests/tests/builtin.rs
particle-builtins/src/builtins.rs

Remove insecured keypair completely.
We use on-chain subnet resolving instead of registry-based.

feat: remove insecured keypair [NET-633]

---

crates/peer-metrics/Cargo.toml
crates/server-config/Cargo.toml
crates/server-config/src/args.rs
crates/server-config/src/defaults.rs
crates/server-config/src/node_config.rs
crates/server-config/src/resolved_config.rs
nox/src/main.rs

Allow to pass --config argument multiple times and allow to pass multiple paths in FLUENCE_CONFIG env.
Want to have a layered configuration: define based things in one file and override them with another config.
[https://linear.app/fluence/issue/NET-594/add-option-to-nox-cli-to-consume-several-configtomls](https://linear.app/fluence/issue/NET-594/add-option-to-nox-cli-to-consume-several-configtomls)
[https://linear.app/fluence/issue/NET-616/remove-unused-options-in-nox-config](https://linear.app/fluence/issue/NET-616/remove-unused-options-in-nox-config)
The initial file for loading is a Config.toml located near the nox binary file but it is not required.
The second priority is all files from FLUENCE_CONFIG env, separated by comma (,)
The last priority is files passed by the --config …

feat(config): add multiple file config sources

---

aquamarine/src/plumber.rs

Allow root to access deactivated workers.
Decider needs to be able to update the worker spell's KV even if the worker is deactivated.

feat(plumber): allow root to access deactivated workers [fixes NET-695]

---

aquamarine/src/actor.rs
aquamarine/src/particle_data_store.rs
aquamarine/src/plumber.rs
nox/src/effectors.rs

In this PR we fix the count of cleanup batch and parallelize deletion.
If cleanup is slow it dramatically decreases the whole system performance. 
- Make a cleanup batch smaller 
- Parallelize deletion
- Now par delete isn't limited by parallel factor, it means if the batch size is 1024 it will produce 1024 tasks and try to run them in parallel. As a result, it will spawn a lot of tasks on the blocking poll which utilize them fully, but it is ok.
- Also introduced an ActorKey which should be used as a datastore key in [NET-632](https://linear.app/fluence/issue/NET-632/use-particlesignature-instead-of-particleid-in-data-store)

fix(cleanup): cleanup par + max batch size

---

crates/server-config/src/defaults.rs
crates/server-config/src/node_config.rs
crates/server-config/src/resolved_config.rs

@nahsi asked:
> Can we make nox to put keys to `BASE_DIR/...` by default instead of `/.fluence`?
It turns out, the current keypair generation does not respect `base_dir` property in config. It always uses `/.fluence` as a base dir, and puts key there.
Load and store keypairs relative to base_dir in Nox config.

fix(config): respect base_dir in keypair generation

---

Cargo.lock
aquamarine/Cargo.toml
aquamarine/src/actor.rs
aquamarine/src/aquamarine.rs
aquamarine/src/lib.rs
aquamarine/src/particle_executor.rs
aquamarine/src/particle_functions.rs
aquamarine/src/plumber.rs
aquamarine/src/spawner.rs
crates/kademlia/src/behaviour.rs
crates/spell-service-api/src/lib.rs
crates/workers/src/error.rs
crates/workers/src/lib.rs
crates/workers/src/persistence.rs
crates/workers/src/scope.rs
crates/workers/src/workers.rs
nox/src/node.rs
particle-builtins/src/builtins.rs
particle-services/src/app_services.rs
sorcerer/src/sorcerer.rs
sorcerer/src/spell_builtins.rs
sorcerer/src/worker_builins.rs

Create a ThreadPool for each worker.
We needed to isolate each worker on a separate CU
[NET-688](https://linear.app/fluence/issue/NET-688/create-a-threadpool-for-each-worker)
- Added a runtime creation on worker creation 
- On the actor creation get a worker runtime handle if it exists 
- Introduced a Spawner entity that allows to shift executions on the different pools

feat(workers): Create a ThreadPool for each worker [fixes NET-688]

---

.github/workflows/e2e.yml
Cargo.lock
crates/created-swarm/src/swarm.rs
crates/nox-tests/tests/workers.rs
crates/nox-tests/tests/workers/test_subnet_resolve_on_worker.air
crates/server-config/src/defaults.rs
crates/subnet-resolver/src/resolve.rs
crates/test-constants/src/lib.rs
crates/workers/src/workers.rs
nox/Cargo.toml
nox/src/main.rs
particle-builtins/src/builtins.rs

Fix crashing workers tokio runtime.
- Added a panic hook
- Enabled io & timer drivers for the worker runtimes 
- Changed UnhandledPanic to Ignore for the worker runtimes
- Subnet resolve is async now
- increased default idle time to 180s

fix(workers): add io+timer drivers to tokio runtimes [fixes NET-795]

---

Cargo.lock
crates/core-manager/Cargo.toml
crates/core-manager/src/core_range.rs
crates/core-manager/src/dev.rs
crates/core-manager/src/errors.rs
crates/core-manager/src/persistence.rs
crates/core-manager/src/strict.rs
crates/hex-utils/Cargo.toml
crates/hex-utils/src/lib.rs

Use hex format for CUIDs instead of byre arrays. 
Byte arrays aren't human-readable
[NET-804](https://linear.app/fluence/issue/NET-804/make-cuid-human-readable)

fix(core-manager)!: use hex format for CUIDs [fixes NET-804]

---

crates/server-config/src/defaults.rs

On 64 core machine, default would be:
```
cpus_range = "1-63"
system_cpu_cores = 3
```

fix(core-mapping): start cpus_range from 1 on 8+ cores

---

Cargo.lock
crates/chain-listener/Cargo.toml
crates/chain-listener/src/lib.rs
crates/chain-listener/src/listener.rs
crates/peer-metrics/src/chain_listener.rs
crates/peer-metrics/src/lib.rs
crates/peer-metrics/src/spell_metrics.rs
nox/src/node.rs

Add some metrics to the ChainListener module. 
Add a pack of metrics:
```rust
pub struct ChainListenerMetrics {
// how many request Nox sends to ccp
ccp_requests_total: Counter,
// how many success replies Nox receives from ccp
// an error is either error from ccp or connection errors
ccp_replies_total: Counter,
// how long we wait for a reply from ccp
ccp_request_duration_msec: Histogram,
// how many proofs we submitted
cpp_proofs_submitted: Counter,
// how many proofs we failed to submit
cpp_proofs_submit_failed: Counter,
// how many proofs transaction are ok
ccp_proofs_tx_success: Counter,
// how many proofs transaction are failed
ccp_proofs_tx_failed: CounterWithExemplar<TxLabel>,
// How many blocks we have received from the newHead subscription
blocks_seen: …
```

feat(metrics): add metrics in chain-listener [NET-806]

---

crates/chain-listener/src/listener.rs
crates/peer-metrics/src/chain_listener.rs

Add new fields `last_seen_block` and `last_processed_block` displaying the block number of the block from newHeader subscription handler.
It will be helpful for alerts to detect chain de-synch
- add `last_seen_block: Gauge` 
- add `last_processed_block: Gauge` 
- use lower bits of the block number in metrics 
- We use `i64` since `u64` and hight aren't supported in prometheus due to [some protobuf restriction](https://github.com/prometheus/client_rust/pull/189)
- It's fine to use only lower bits of the u256 block number since:
1. most likely, we won't reach i64 _soon_
2. these metrics will be used in alerts to detect the chain de-sync, lower bits should be enough for this task.

fix: add block number value to the metrics

---

crates/chain-listener/src/listener.rs

Clear proof counters in case of epoch change inside refresh method. 
Otherwise, in case of websocket disconnect and epoch change peer won't reset proof counters and won't send any proofs.

fix(chain-listener): reset proof counters on new epoch in refresh [NET-813]

---

crates/chain-listener/src/listener.rs
crates/core-manager/src/dev.rs
crates/core-manager/src/dummy.rs
crates/core-manager/src/manager.rs
crates/core-manager/src/strict.rs

[Provide a brief description of the changes introduced by this pull request and the motivation behind them.]
[Explain why these changes are necessary or beneficial. Discuss any problems or limitations with the current implementation that this pull request addresses.]
[List the specific changes and additions introduced by this pull request.]
[Add any relevant screenshots or animated GIFs to showcase the changes.]
[Provide any additional information or context that may be helpful for the reviewer.]

fix(listener): fixed core acquire

---

crates/core-manager/src/strict.rs

Fix the reassignment CPU requirements calculation

fix(core-manager): reassignment

---

particle-builtins/src/builtins.rs
particle-modules/src/modules.rs

Change effectors loading in dev mode.
Now, in the dev mode, we use settings from `dev_mode.binaries` for the effectors's module configs, ignoring the `effectors` setting. To set it up, a user must manually edit Nox's config if they want their modules to use those binaries in the dev mode. That's hard and isn't supported by FCLI. However, FCLI support the `effectors` config, which is now ignored in the dev mode.
This PR, when Nox encounters a module which `effectors` configuration, it takes the config from there, not from `dev_mode.binaries`.
- In the dev mode, if a module is configured as an effector, try to take config for it from `effectors`. If no effector is configured, try to take from the default list of binaries for a module.
- Also, allow anyone to use `aqua-ipfs` service in the …

fix(dev-mode): change effector config usage in dev-mode

---

crates/vm-utils/src/lib.rs
crates/vm-utils/src/vm_utils.rs
crates/workers/src/workers.rs

Pause VMs on worker deactivation and resume on activation
To reflect the deal state on chain
- Tested manually, deactivation and activation worked as expected

fix: suspend/resume on worker deactivate/activate

---

crates/gpu-utils/src/lib.rs
crates/vm-utils/src/vm_utils.rs

Allow only NVidia and AMD GPUs.  This way we try to increase the probability that iGPU aren't imported. Still need to point out that at least AMD iGPUs exist.

fix(vm): allow only nvidia and amd gpus

---

crates/server-config/src/defaults.rs

default_min_batch_count=5
default_max_batch_count=30
default_max_proof_batch_size=128
default_system_cpu_count=1
default_cpus_range=1-total # we always leave 1 core to OS

feat(config,cpu,proofs): change cpu and batching defaults

---

crates/server-config/src/defaults.rs

Folex asked to change those, dunno why

fix(config): change defaults for batching

---

crates/created-swarm/src/swarm.rs
nox/src/main.rs
nox/src/node.rs
particle-builtins/src/builtins.rs

[Provide a brief description of the changes introduced by this pull request and the motivation behind them.]
[Explain why these changes are necessary or beneficial. Discuss any problems or limitations with the current implementation that this pull request addresses.]
[List the specific changes and additions introduced by this pull request.]
[Add any relevant screenshots or animated GIFs to showcase the changes.]
[Provide any additional information or context that may be helpful for the reviewer.]

fix(logs): add peer id in run-console log

---

Cargo.lock
crates/chain-listener/src/listener.rs
crates/peer-metrics/src/chain_listener.rs
crates/peer-metrics/src/info.rs
crates/peer-metrics/src/lib.rs
crates/server-config/Cargo.toml
crates/server-config/src/network_config.rs
nox/src/behaviour/network.rs
nox/src/node.rs

Add a chain info metric with chain configuration
- Refactor a bit to remove `server-config` dependency on `peer-metrics`. It turned out to be useless in this PR, but maybe will be helpful in the next one with more configs
- Add `current_commitment_status`. The status is a number which corresponds to the CCStatus enum in chain_listener.
- Add `nox_chain_info` metric. Example:
```
nox_chain_info{peer_id="0x123",http_endpoint="http://localhost:8545",diamond_contract_address="0x123",network_id="1",default_base_fee="1",default_priority_fee="1",ws_endpoint="ws://localhost:8546",proof_poll_period="1s",min_batch_count="1",max_batch_count="1",max_proof_batch_size="1",epoch_end_window="1s"} 1
```

feat(metrics): add chain info metrics

---

.github/workflows/e2e.yml
crates/chain-listener/src/listener.rs
crates/peer-metrics/src/chain_listener.rs
crates/peer-metrics/src/info.rs
crates/peer-metrics/src/lib.rs
crates/server-config/src/node_config.rs
nox/src/node.rs

Add Info metrics with the used nox config
Used Nox Settings:
- Network Info
```
pub tcp_port: u16,
pub websocket_port: u16,
pub listen_ip: String,
pub network_type: String,
pub bootstrap_nodes: Addresses,
pub external_address: Option<String>,
pub external_multiaddresses: Addresses,
```
- Vm Info
```
pub allow_gpu: u8,
pub public_ip: String,
pub host_ssh_port: u16,
pub vm_ssh_port: u16,
pub port_range: String,
```
- System Info
```
pub cpus_range: String,
pub system_cpu_count: usize,
pub particle_execution_timeout_sec: u64,
pub max_spell_particle_ttl_sec: u64,
```
Looks like this:
```
nox_build_info{node_version="0.1.0",air_version="0.1.0",spell_version="0.1.0"} 1
nox_chain_info{peer_id="peer_id",http_endpoint="",diamond_contract_address="",network_id="0",default_base_fee="",default_priorit …
```

feat(metrics): add info nox config metrics

---

crates/chain-listener/src/listener.rs
crates/peer-metrics/src/chain_listener.rs

Add more CC metrics:
```
// max amount of proofs are allowed
ccp_proofs_per_epoch_allowed_max: Gauge,
// min amount of proofs are allowed
ccp_proofs_per_epoch_allowed_min: Gauge,
// CUs metrics
cus_total: Gauge,
cus_in_deals: Gauge,
// Epoch Metrics
current_epoch: Gauge,
current_epoch_start_timestamp_sec: Gauge,
current_epoch_duration_sec: Gauge,
```

feat(metrics): add CC metrics

---

crates/vm-utils/src/vm_utils.rs

Close libvirt connection when we're done.
We found a problem with `Too many files` on one of our provider's machines when deploying a deal on it: the nox process has too many open eventfd connections. Further investigation showed that the problem is that the `Connection` struct of the `virt` crate doesn't implement `Drop`, so the connection isn't closed. 
Auto-close connection.

fix(vm): close libvirt connections
