fluencelabs/nox

crypto/jvm/src/main/scala/fluence/crypto/algorithm/Ecdsa.scala, crypto/jvm/src/main/scala/fluence/crypto/algorithm/JavaAlgorithm.scala, crypto/jvm/src/test/scala/fluence/crypto/SignatureSpec.scala, crypto/src/main/scala/fluence/crypto/FileKeyStorage.scala, crypto/src/main/scala/fluence/crypto/SignAlgo.scala, crypto/src/main/scala/fluence/crypto/algorithm/DumbSign.scala, crypto/src/main/scala/fluence/crypto/algorithm/KeyGenerator.scala, crypto/src/main/scala/fluence/crypto/algorithm/SignatureFunctions.scala, crypto/src/main/scala/fluence/crypto/signature/SignatureChecker.scala, crypto/src/main/scala/fluence/crypto/signature/Signer.scala, dataset/client/src/main/scala/fluence/dataset/BasicContract.scala, dataset/client/src/main/scala/fluence/dataset/contract/ContractRead.scala, dataset/client/src/main/scala/fluence/dataset/contract/ContractWrite.scala, dataset/grpc/src/test/scala/fluence/dataset/grpc/BasicContractCodecSpec.scala, dataset/node/src/main/scala/fluence/dataset/node/ContractAllocator.scala, dataset/node/src/main/scala/fluence/dataset/node/Contracts.scala, dataset/node/src/main/scala/fluence/dataset/node/ContractsCache.scala, dataset/node/src/test/scala/fluence/dataset/node/ContractAllocatorSpec.scala, dataset/node/src/test/scala/fluence/dataset/node/ContractsCacheSpec.scala, dataset/node/src/test/scala/fluence/dataset/node/ContractsSpec.scala, kademlia/testkit/src/main/scala/fluence/kad/testkit/TestKademlia.scala, node/src/main/scala/fluence/node/NodeComposer.scala, node/src/main/scala/fluence/node/NodeServices.scala, node/src/test/scala/fluence/node/NodeComposerSpec.scala, storage/rocksdb/src/test/scala/fluence/storage/rocksdb/RocksDbStoreSpec.scala
store in private key only S, in public key only Q point without wrappers
=> refactor sign classes

build.sbt, crypto/jvm/src/main/scala/fluence/crypto/algorithm/Ecdsa.scala, dataset/node/src/main/scala/fluence/dataset/node/storage/Datasets.scala, kademlia/grpc/src/main/protobuf/grpc.proto, kademlia/grpc/src/main/scala/fluence/kad/grpc/KademliaNodeCodec.scala, kademlia/protocol/build.sbt, kademlia/protocol/src/main/scala/fluence/kad/protocol/Contact.scala, node/src/main/resources/reference.conf, node/src/main/scala/fluence/node/NodeApp.scala, node/src/main/scala/fluence/node/NodeComposer.scala, node/src/test/scala/fluence/node/NetworkSimulationSpec.scala, node/src/test/scala/fluence/node/NodeComposerSpec.scala, project/SbtCommons.scala, transport/grpc/src/main/resources/reference.conf, transport/grpc/src/main/scala/fluence/transport/grpc/server/GrpcServer.scala, transport/grpc/src/main/scala/fluence/transport/grpc/server/GrpcServerConf.scala, transport/grpc/src/main/scala/fluence/transport/grpc/server/UPnP.scala
- check that dataset is stored by this node
=> kad.Contact with scodec; dataset with contract check

client/cli-app/js/src/main/scala/fluence/client/LastResult.scala, client/cli-app/js/src/main/scala/fluence/client/Main.scala, client/cli-app/js/src/main/scala/fluence/client/RangeElement.scala, client/core/src/main/scala/fluence/client/core/ClientReplicationWrapper.scala, dataset/client/src/main/scala/fluence/dataset/client/ClientRange.scala, dataset/grpc/js/src/main/scala/fluence/dataset/grpc/client/DatasetStorageClient.scala
=> js range requests

node/core/src/main/scala/fluence/node/core/NodeComposer.scala, storage/core/jvm/src/main/scala/fluence/kvstore/InMemoryKVStore.scala, storage/core/jvm/src/test/scala/fluence/kvstore/InMemoryKVStoreSpec.scala, storage/core/src/main/scala/fluence/kvstore/KVStore.scala, storage/core/src/test/scala/fluence/kvstore/KVStorageSpec.scala, storage/core/src/test/scala/fluence/kvstore/TestKVStore.scala, storage/rocksdb/src/main/scala/fluence/kvstore/rocksdb/RocksDbFactory.scala, storage/rocksdb/src/main/scala/fluence/kvstore/rocksdb/RocksDbKVStore.scala, storage/rocksdb/src/test/scala/fluence/kvstore/rocksdb/RocksDbKVStoreSpec.scala
Added documentation for KVStore usage. And made possibility to create storage with codecs and snapshot.
=> Rocks db kv store

build.sbt, project/SbtCommons.scala, vm/src/main/resources/reference.conf, vm/src/main/scala/fluence/vm/VmError.scala, vm/src/main/scala/fluence/vm/WasmVm.scala, vm/src/main/scala/fluence/vm/config/VmConfig.scala, vm/src/test/resources/wast/counter.wast, vm/src/test/resources/wast/mul.wast, vm/src/test/resources/wast/sum-copy.wast, vm/src/test/resources/wast/sum-with-trap.wast, vm/src/test/resources/wast/sum.wast, vm/src/test/scala/fluence/vm/WasmVmSpec.scala, vm/src/test/scala/fluence/vm/vm.scala
In order to enable stateful computations, we take Asmble (WebAssembly VM implementation) as a dependency.
In this commit, initial VM client integration is made.
=> Asmble (WebAssembly VM) initial integration

.travis.yml, vm/src/main/resources/reference.conf, vm/src/main/scala/fluence/vm/VmError.scala, vm/src/main/scala/fluence/vm/WasmVm.scala, vm/src/test/scala/fluence/vm/WasmVmSpec.scala
Updated error classes for better tracking of VM errors.
=> VM (Wasm) Errors hierarchy

.travis.yml, build.sbt, project/SbtCommons.scala, vm/src/main/resources/reference.conf, vm/src/main/scala/fluence/vm/ModuleInstance.scala, vm/src/main/scala/fluence/vm/VmError.scala, vm/src/main/scala/fluence/vm/WasmVm.scala, vm/src/main/scala/fluence/vm/WasmVmImpl.scala, vm/src/main/scala/fluence/vm/package.scala, vm/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, vm/src/test/resources/wast/counter-copy.wast, vm/src/test/scala/fluence/vm/ModuleInstanceSpec.scala, vm/src/test/scala/fluence/vm/TestUtils.scala, vm/src/test/scala/fluence/vm/WasmVmImplSpec.scala, vm/src/test/scala/fluence/vm/WasmVmSpec.scala
VM Module definition, basic trait and its implementation.
=> Getting Vm state

.travis.yml, bootstrap/.gitignore, bootstrap/contracts/Deployer.sol, bootstrap/contracts/Migrations.sol, bootstrap/migrations/1_initial_migration.js, bootstrap/package-lock.json, bootstrap/package.json, bootstrap/test/TestDeployer.js, bootstrap/truffle.js
- `Deployer.sol` is the main contract
- `Migration.sol` and all other migration-something files are generated Truffle helper files
- `truffle.js` is a config file for Truffle
To run tests:
```
$ cd bootstrap
$ npm install
$ npm test
```
Please feel free to criticize everything and especially performance and naming-related things.
=> Deployer.sol contract for bootstrapping cluster of Solvers (#47)

.gitignore, build.sbt, project/SbtCommons.scala, project/plugins.sbt, vm/examples/README.md, vm/examples/counter/Cargo.toml, vm/examples/counter/src/main/rust/counter.rs, vm/examples/counter/src/main/scala/fluence/vm/examples/CounterRunner.scala, vm/examples/runExample.sh, vm/src/main/scala/fluence/vm/WasmVm.scala, vm/src/test/scala/fluence/vm/WasmVmSpec.scala
* Fix lazy logger initialization error
* Counter in Rust
* Task for compiling and running examples
* remove extra empty lines
* Using IOApp for IO oriented programs
=> Rust example for Data Engine

CONTRIBUTING.md, README.md
Added the very basic `README.md` describing what the project is all about. 
Also fixed an incorrect license attribution in `CONTRIBUTING.md`: it was "AGPL", but should have been `Apache 2.0`.
=> Basic readme

externalstorage/src/main/scala/fluence/swarm/MutableResourceIdentifier.scala, externalstorage/src/main/scala/fluence/swarm/crypto/Keccak256Hasher.scala, externalstorage/src/main/scala/fluence/swarm/crypto/Secp256k1Signer.scala, externalstorage/src/main/scala/fluence/swarm/helpers/ByteVectorJsonCodec.scala, externalstorage/src/main/scala/fluence/swarm/meta/RootAddr.scala, externalstorage/src/test/scala/fluence/swarm/InitializeRequestSpec.scala, externalstorage/src/test/scala/fluence/swarm/SwarmClientIntegrationSpec.scala, project/SbtCommons.scala, statemachine/src/main/scala/fluence/statemachine/state/TendermintStateHolder.scala, statemachine/src/test/scala/fluence/statemachine/IntegrationSpec.scala, statemachine/src/test/scala/fluence/statemachine/state/MerkleHashSpec.scala, vm/src/test/scala/fluence/vm/ModuleInstanceSpec.scala, vm/src/test/scala/fluence/vm/TestUtils.scala, vm/src/test/scala/fluence/vm/WasmVmImplSpec.scala, vm/src/test/scala/fluence/vm/WasmVmSpec.scala
Only applying forgotten auto-formating, nothing more.
=> Apply forgotten auto-formatting

build.sbt, js-client/package.json, js-client/src/Client.ts, js-client/src/Engine.ts, js-client/src/Result.ts, js-client/src/ResultAwait.ts, js-client/src/Session.ts, js-client/src/SessionConfig.ts, js-client/src/Signer.ts, js-client/src/TendermintClient.ts, js-client/src/examples/CustomCommands.ts, js-client/src/examples/IncrementAndMultiply.ts, js-client/src/main.ts, js-client/src/responses.ts, js-client/src/tx.ts, js-client/src/utils.ts, js-client/tendermint.d.ts, js-client/tsconfig.json, statemachine/local-cluster-commands/start.sh, statemachine/src/main/scala/fluence/statemachine/state/QueryProcessor.scala, statemachine/src/main/scala/fluence/statemachine/tx/SessionSummary.scala, statemachine/src/main/scala/fluence/statemachine/tx/TransactionStatus.scala, statemachine/src/main/scala/fluence/statemachine/tx/TxParser.scala, statemachine/src/main/scala/fluence/statemachine/util/Crypto.scala, statemachine/src/main/scala/fluence/statemachine/util/HexCodec.scala
=> Session enhancement

.travis.yml, js-client/README.md, js-client/package.json, js-client/src/Result.ts, js-client/src/TendermintClient.ts, js-client/src/examples/CustomCommands.ts, js-client/src/examples/DbClient.ts, js-client/src/examples/IncrementAndMultiply.ts, js-client/src/examples/QuotationClient.ts, js-client/src/utils.ts, statemachine/src/main/scala/fluence/statemachine/tx/FunctionCallDescription.scala, statemachine/src/main/scala/fluence/statemachine/tx/VmOperationInvoker.scala
- convert byte array of the state machine to hex string
- npm package for publishing
- fix regex
=> Js client string support

vm/examples/llamadb/src/main/rust/lib.rs, vm/examples/llamadb/src/main/rust/tests.rs, vm/examples/llamadb/src/main/scala/fluence/vm/examples/LlamaDbRunner.scala
Added test cases and usage examples for DELETE and TRUNCATE statements.
=> Llamadb tests 

.travis.yml, build.sbt, sdk/rust/Cargo.toml, sdk/rust/src/lib.rs, sdk/rust/src/logger/mod.rs, statemachine/docker/examples/vmcode-llamadb/llama_db.wasm, statemachine/docker/solver/sm.config, vm/examples/llamadb/Cargo.toml, vm/examples/llamadb/src/main/rust/lib.rs, vm/examples/llamadb/src/main/rust/tests.rs, vm/examples/llamadb/src/main/scala/fluence/vm/examples/LlamaDbRunner.scala, vm/src/main/resources/reference.conf, vm/src/main/scala/fluence/vm/WasmVm.scala, vm/src/main/scala/fluence/vm/config/VmConfig.scala
- Applies the last version of 'asemle' (fixed problem with merge strategy for asm)
- Creates SDK logger module.
- Applies SDK logger to Llama_db wrapper
Today later will be added examples for using this logger.
=> Wasm logger

bootstrap/package-lock.json, bootstrap/package.json, bootstrap/unlock-keys.js, cli/Cargo.toml, cli/src/main.rs, cli/src/register.rs, tools/run/compose.sh, tools/run/node.yml, tools/run/parity.yml, tools/run/swarm.yml
- Updates deploy script
- CLI can decode base64 tendermint key
- A small script to decode ethereum keystore to a private key
=> Deploy script

cli/Cargo.lock, cli/Cargo.toml, cli/README.md, cli/src/command.rs, cli/src/contract_status/mod.rs, docs/guides/backend.md, docs/guides/kickstart.md, docs/guides/miner.md, node/src/main/resources/docker/entrypoint.sh, node/src/main/resources/reference.conf, node/src/main/scala/fluence/node/workers/tendermint/config/TendermintConfig.scala, project/SbtCommons.scala, tools/deploy/fabfile.py, tools/deploy/scripts/compose.sh, tools/deploy/scripts/node.yml
=> add hard-coded contract address

.gitmodules
So git and IDE know how to pull changes from remote
=> Specify branch for book submodule

tools/deploy/fabfile.py
FAQ.
Q: Why aren't you using `snap install docker`?
A: I've tried, there were lots of bugs and misbehaviours, but I can't recall details
Q: Have you tested it?
A: Yep, just added 4 nodes to the Devnet this way.
=> Automate docker & docker-compose installation

node/src/it/scala/fluence.node/MasterNodeSpec.scala, node/src/it/scala/fluence.node/TestWorkersPool.scala, node/src/main/scala/fluence/node/MakeResource.scala, node/src/main/scala/fluence/node/config/NodeConfig.scala, node/src/main/scala/fluence/node/workers/DockerWorkersPool.scala, node/src/main/scala/fluence/node/workers/Worker.scala, node/src/main/scala/fluence/node/workers/WorkerP2pConnectivity.scala
This PR should help not only with the code maintenance but also with some rare bugs.
=> DockerWorkersPool.runWorker refactored

dashboard/src/front/components/fluence-deployable-app/snippets.tsx
=> Use upload snippet for Redis

dashboard/src/fluence/deployable/index.ts
Fixed bugs:
- bug with incorrect initialization of cjson module of Lua
- bug with unpaired quotes in requests
Resolves #726 #725
=> Update redis to v0.4

dashboard/src/fluence/deployable/index.ts
=> Update wasm app to v0.5

dashboard/src/fluence/deployable/index.ts
=> add wasm sqlite v0.1

build.sbt, node/testkit/src/test/scala/fluence/node/BlockUploadingIntegrationSpec.scala, statemachine/src/main/scala/fluence/statemachine/AbciHandler.scala, statemachine/src/main/scala/fluence/statemachine/AbciService.scala, statemachine/src/main/scala/fluence/statemachine/TxCode.scala, statemachine/src/main/scala/fluence/statemachine/state/AbciState.scala, statemachine/src/main/scala/fluence/statemachine/state/Sessions.scala, statemachine/src/test/scala/fluence/statemachine/AbciServiceSpec.scala, statemachine/src/test/scala/fluence/statemachine/StatemachineIntegrationSpec.scala
I have also refactored `TxResponse.Code` a little bit, so it is more informs clients better
=> Integration test on block uploading + abci service

backend-sdk/Cargo.toml, backend-sdk/crates/macro/Cargo.toml, backend-sdk/crates/macro/src/lib.rs, backend-sdk/crates/main/Cargo.toml, backend-sdk/crates/main/src/lib.rs, backend-sdk/src/lib.rs
=> bump dyn version to 0.15.44

.circleci/config.yml, build.sbt, effects/swarm/src/main/scala/fluence/effects/swarm/helpers/SignatureDataOps.scala, fluence-js/package-lock.json, kademlia/http/src/main/scala/fluence/kad/http/KademliaHttpNode.scala, kademlia/http/src/test/scala/fluence/kad/http/KademliaHttpSpec.scala, kademlia/src/main/scala/fluence/kad/Kademlia.scala, kademlia/testkit/src/test/scala/fluence/kad/KademliaSimulationSpec.scala, node/src/main/scala/fluence/node/workers/tendermint/DhtReceiptStorage.scala, node/src/test/scala/fluence/node/ControlRpcSpec.scala, project/SbtCommons.scala, vm/src/test/scala/fluence/vm/WasmVmSpec.scala
=> Basic tests for KademliaHttp (including DHT)

backend-sdk/Cargo.toml, backend-sdk/crates/macro/Cargo.toml, backend-sdk/crates/macro/src/lib.rs, backend-sdk/crates/macro/src/macro_attr_parser.rs, backend-sdk/crates/main/Cargo.toml, backend-sdk/crates/main/src/lib.rs, backend-sdk/crates/main/src/memory/mod.rs, backend-sdk/src/lib.rs
=> Add attrs for side modules

backend-sdk/Cargo.toml, backend-sdk/crates/macro/Cargo.toml, backend-sdk/crates/macro/src/lib.rs, backend-sdk/crates/main/Cargo.toml, backend-sdk/crates/main/src/lib.rs, backend-sdk/crates/main/src/logger/mod.rs, backend-sdk/src/lib.rs, project/VmSbt.scala, vm/frank/Cargo.lock, vm/frank/Cargo.toml, vm/frank/src/frank.rs, vm/frank/src/jni/exports.rs
=> Optimize logging

effects/ethclient/src/main/scala/fluence/effects/ethclient/EthClient.scala, effects/resources/src/main/scala/fluence/effects/resources/MakeResource.scala, effects/tendermint-rpc/src/main/scala/fluence/effects/tendermint/rpc/websocket/TendermintWebsocketRpcImpl.scala, effects/tendermint-rpc/src/test/scala/fluence/effects/tendermint/rpc/TestWRpc.scala, effects/tendermint-rpc/src/test/scala/fluence/effects/tendermint/rpc/WebsocketRpcSpec.scala, effects/testkit/src/main/scala/fluence/effects/testkit/Timed.scala, node/src/main/scala/fluence/node/eth/NodeEth.scala
=> Fix 'subscribe and receive messages' in WebsocketRpcSpec

crates/libp2p/src/serde.rs, faas-api/src/address.rs, server/src/behaviour/server_behaviour.rs, server/src/config/fluence_config.rs, server/src/function/builtin_service.rs, server/src/function/config.rs, server/src/function/dht_names.rs, server/src/function/execution.rs, server/src/function/peers.rs, server/src/function/router.rs, server/src/function/router_behaviour.rs, server/src/function/wait_peer.rs, server/src/function/waiting_queues.rs, server/src/lib.rs, server/src/server.rs, server/tests/routing.rs, server/tests/utils/misc.rs, trust-graph/src/certificate.rs, trust-graph/src/certificate_serde.rs, trust-graph/src/trust_graph.rs, trust-graph/src/trust_node.rs
Call it like this:
```json
call: {
"uuid": "UUID-1",
"target": "fluence:/service/identify",
"reply_to": "fluence:/peer/QmeMG7qPvV7MC1xCgQVBRVXp3w5mH45v61Prkdh7V9Nj2x/client/QmTXDHpnq1teecFedJtDxDRog4rBEdShJoByYm1eLfehku",
"arguments": {
"msg_id": "5a79e495-48a4-494c-84a2-74bde98155c9"
}
}
```
Response would look like this:
```json
{
"uuid": "ed5ec735-c36e-4c59-aa7d-56416fdc01df",
"target": "fluence:/client/QmTXDHpnq1teecFedJtDxDRog4rBEdShJoByYm1eLfehku",
"reply_to": "fluence:/peer/12D3KooWFufaFPYGPZ2h5E4mNkFTopVnfMAHaD25PRTixxqBfkQp",
"arguments": {
"addresses": [
"/ip4/1.2.3.4/tcp/7001",
"/ip4/1.2.3.4/tcp/9001/ws",
],
"msg_id": "5a79e495-48a4-494c-84a2-74bde98155c9"
},
"name": "reply on identify"
}
```
=> Identify builtin service

Cargo.lock, deploy/Config.toml, server/Cargo.toml, server/Config.toml, server/src/app_service/behaviour.rs, server/src/behaviour/server_behaviour.rs, server/src/config/fluence_config.rs, server/src/faas/behaviour.rs, server/src/function/builtin_service.rs, server/src/function/dht_names.rs, server/src/function/errors.rs, server/src/function/execution.rs, server/src/function/router.rs, server/src/function/router_behaviour.rs, server/src/function/services.rs, server/src/lib.rs, server/src/server.rs, server/tests/routing.rs, server/tests/utils/faas.rs, server/tests/utils/misc.rs
Related to https://github.com/fluencelabs/fce/pull/13
=> Use AppService instead of Faas

Cargo.lock, deploy/Config.toml, deploy/deployment_config.json, deploy/fluence.py, deploy/fluence_bootstrap.yml, deploy/ipfs_node_config.toml, server/src/app_service/blueprint.rs, server/src/config/app_services.rs, server/src/config/defaults.rs, server/src/config/fluence_config.rs, server/src/function/dht_names.rs, server/src/function/errors.rs, server/src/function/execution.rs, server/src/function/router.rs, server/src/function/services.rs, server/src/function/wait_address.rs, server/tests/routing.rs, server/tests/utils/misc.rs
If client haven't provided blueprint id, it will be generated automatically by Serde on deserialization
=> Blueprint id generation

particle-modules/src/file_names.rs, particle-modules/src/files.rs, particle-modules/src/lib.rs, particle-services/src/app_services.rs, particle-services/src/error.rs, particle-services/src/lib.rs, particle-services/src/persistence.rs, particle-services/src/vm.rs
=> Service persistence

.circleci/config.yml, Cargo.lock, README.md, client/rust-libp2p/Cargo.toml, crates/config-utils/Cargo.toml, crates/libp2p/Cargo.toml, crates/libp2p/src/macros.rs, crates/libp2p/src/serde.rs, crates/libp2p/src/transport.rs, crates/server-config/Cargo.toml, crates/test-utils/Cargo.toml, particle-actors/Cargo.toml, particle-behaviour/Cargo.toml, particle-closures/Cargo.toml, particle-closures/src/builtin_services_api.rs, particle-closures/src/mailbox.rs, particle-dht/Cargo.toml, particle-dht/src/dht.rs, particle-dht/src/kademlia.rs, particle-dht/src/publish.rs, particle-dht/src/resolve.rs, particle-protocol/Cargo.toml, particle-protocol/src/libp2p_protocol/upgrade.rs, particle-server/Cargo.toml, particle-server/src/bootstrapper/behaviour.rs, particle-server/src/server.rs, particle-server/tests/chat/chat.rs, trust-graph/Cargo.toml
I've tested the dashboard with that PR, it works.
=> Update libp2p version

.circleci/config.yml, .github/workflows/rust_ci.yml, .github/workflows/rustdoc.yml, crates/kademlia/src/lib.rs, crates/test-utils/src/misc.rs, particle-closures/src/host_closures.rs, particle-node/src/lib.rs, particle-node/tests/builtin.rs, particle-services/src/app_services.rs, particle-services/src/error.rs
`get_interface` and `remove` now can accept aliases  as well as ids
=> Add resolve_alias builtin, update srv builtins

Cargo.lock, crates/server-config/src/defaults.rs, particle-node/Cargo.toml, particle-node/src/main.rs
=> Print management key encoding in libp2p-js compatible format

particle-closures/src/host_closures.rs, particle-node/tests/builtin.rs
=> op array_length

crates/builtins-deployer/src/builtins_deployer.rs, crates/created-swarm/src/swarm.rs, crates/server-config/src/defaults.rs, crates/server-config/src/node_config.rs, particle-node/src/main.rs
timeout is `particle_execution_timeout * 5`
=> autodeploy: wait for vm pool is ready

particle-builtins/src/builtins.rs, particle-node/tests/builtin.rs
For empty, `"<empty argument list>"`
For single argument, it's JSON representation
For multiple arguments, list of JSON representations
=> implement "debug stringify" builtin

Cargo.lock, Cargo.toml, crates/particle-args/Cargo.toml, crates/particle-args/src/args.rs, crates/particle-args/src/args_error.rs, crates/server-config/src/defaults.rs, crates/server-config/src/node_config.rs
To avoid timeouts on slow trust-graph calls when node starts.
Also improved error messages in builtins args deserialization
=> Increase default auto_particle_ttl

particle-node/tests/builtin.rs
```
assert_eq!(
result.pointer("/result/0/functions_stats/0/stats/success_req_count"),
Some(&json!(1))
);
```
=> Improve test using `JValue::pointer`

Cargo.lock, Cargo.toml, aquamarine/src/actor.rs, aquamarine/src/aqua_runtime.rs, aquamarine/src/aquamarine.rs, aquamarine/src/particle_executor.rs, aquamarine/src/plumber.rs, crates/local-vm/src/local_vm.rs, particle-node/src/behaviour/network.rs, particle-node/src/node.rs
=> feat: set current_peer_id on every particle execution

Cargo.lock, aquamarine/src/aquamarine.rs, aquamarine/src/command.rs, aquamarine/src/plumber.rs, particle-builtins/src/builtins.rs, particle-builtins/src/debug.rs, particle-builtins/src/particle_function.rs, particle-execution/src/particle_function.rs, particle-node/Cargo.toml, particle-node/download_spell.sh, particle-node/src/node.rs, particle-node/tests/spells.rs, particle-services/src/app_services.rs, sorcerer/Cargo.toml, sorcerer/src/lib.rs, sorcerer/src/script_executor.rs, sorcerer/src/sorcerer.rs, sorcerer/src/spells.rs, sorcerer/src/utils.rs
closes NET-296, NET-297, NET-300
=> feat(spells): read arguments, store results and handle errors

crates/created-swarm/src/swarm.rs, crates/fs-utils/src/lib.rs, crates/server-config/src/defaults.rs, crates/server-config/src/dir_config.rs, crates/server-config/src/lib.rs, crates/server-config/src/resolved_config.rs, particle-builtins/src/builtins.rs, particle-node/src/node.rs
fixes issue with /private symlink prefix for mac os
=> fix(config): refactor configs and canonicalize all paths

Cargo.lock, crates/spell-event-bus/Cargo.toml, crates/spell-event-bus/src/api.rs, crates/spell-event-bus/src/bus.rs, crates/spell-event-bus/src/config.rs, particle-node/tests/spells.rs, sorcerer/src/sorcerer.rs
* unit tests for spell event bus
* test for connection-pool events
=> chore(spell): add tests for spells

aquamarine/src/plumber.rs, crates/key-manager/src/key_manager.rs, particle-node/src/node.rs, particle-services/src/app_service.rs, particle-services/src/app_services.rs, particle-services/src/persistence.rs, sorcerer/src/spells.rs
+  fix spell.install for global scope
=> fix(spells): allow global aliases for builtin spells

aquamarine/src/actor.rs, aquamarine/src/lib.rs, aquamarine/src/log.rs, aquamarine/src/particle_functions.rs, particle-node/src/main.rs
Since the introduction of Deal Spells, we have suffered an explosion in volume of logs. I think it is time to address that issue, and this PR is an attempt to find right balance between observability, performance and ergonomics.
=> feat(logs)!: reduce logs

crates/server-config/src/args.rs
=> fix(config): aqua-pool-size argument

aquamarine/src/actor.rs, aquamarine/src/log.rs, aquamarine/src/particle_executor.rs, aquamarine/src/particle_functions.rs, aquamarine/src/plumber.rs, crates/nox-tests/tests/builtin.rs, crates/nox-tests/tests/spells.rs, nox/src/dispatcher.rs
Adds a span propagation with the additional deal_id tracing information.
Simplify the passing of the contextual information for debugging (i.e deal_id)
https://linear.app/fluence/issue/NET-493/small-span-demo
=> feat(tracing): introduce deal_id-based trace logs to particle execution

Cargo.lock, crates/system-services/Cargo.toml
Update decider version to 0.4.17. It's a version released after major decider's refactoring.
Keep decider updated to use new features. Check that new decider works.
=> feat(decider): update to 0.4.17

Cargo.lock, crates/system-services/Cargo.toml
[Provide a brief description of the changes introduced by this pull request and the motivation behind them.]
[Explain why these changes are necessary or beneficial. Discuss any problems or limitations with the current implementation that this pull request addresses.]
[List the specific changes and additions introduced by this pull request.]
[Add any relevant screenshots or animated GIFs to showcase the changes.]
[Provide any additional information or context that may be helpful for the reviewer.]
=> feat: update decider

aquamarine/src/lib.rs, crates/kademlia/src/behaviour.rs, crates/kademlia/src/lib.rs, nox/src/lib.rs, nox/src/tasks.rs, particle-protocol/src/libp2p_protocol/upgrade.rs, particle-services/src/app_services.rs, particle-services/src/lib.rs, rust-toolchain.toml
https://github.com/rust-lang/rust/issues/43244
=> chore: update toolchain to nightly-2023-08-27

aquamarine/src/particle_data_store.rs, particle-execution/src/particle_vault.rs
Fixed wrong api usage.
Trying to remove files, but it is dirs
=> fix(datastore): remove directories

Cargo.toml
```
avm-server = "=0.35.0"
air-interpreter-wasm = "=0.59.0"
```
=> fix(deps)!: avm server 0.35 aquavm 0.59

aquamarine/src/vm_pool.rs, crates/connected-client/src/connected_client.rs, crates/created-swarm/src/swarm.rs, crates/nox-tests/tests/builtin.rs, crates/nox-tests/tests/chain_listener.rs, crates/nox-tests/tests/network/network_explore.rs, crates/nox-tests/tests/spells.rs, crates/nox-tests/tests/topology.rs, crates/test-constants/src/lib.rs, nox/src/behaviour/network.rs, nox/src/connectivity.rs, nox/src/health.rs
Added a kademlia bootstrap health check.
I hope it will fix some tests + reduce test difficulty related to Kad timeouts.
- nox node initialization is a parallel now
- fixed span names in tests
=> feat(health): add kademlia bootstrap healthcheck + fix test span logging

Cargo.lock, crates/core-manager/Cargo.toml, crates/core-manager/src/manager.rs
Use a receiver stream instream for the persistent task
=> fix(core-manager): process core persistence in a stream

crates/core-manager/src/errors.rs, crates/core-manager/src/manager.rs
Improve logging info for core manager assignment.
=> fix(core-manager): add logging info

.github/workflows/rustdoc.yml
rustdoc step always failed because hwloc was missing
=> chore(ci): fix rustdoc

crates/server-config/src/defaults.rs, crates/server-config/src/node_config.rs
Changed the default behaviour for the cpu range
Do not use kernel cores for the big machines.
=> fix(config): change default for the cpu range in nox

crates/chain-connector/src/connector.rs, crates/chain-connector/src/function/capacity.rs, crates/chain-connector/src/function/core.rs
Support fluencelabs/deal#349 changes. `difficulty` now is in Core contract
=> feat: support new contracts

Cargo.lock, crates/chain-connector/Cargo.toml, crates/chain-connector/src/connector.rs, crates/chain-connector/src/lib.rs, crates/chain-data/src/utils.rs, crates/chain-listener/src/listener.rs, crates/core-manager/src/strict.rs, nox/src/node.rs
Generic cnain connector.
Allows to mock it in tests
=> fix(chain-connector): make connector generic

crates/server-config/src/resolved_config.rs, docker/Config.default.toml, docker/Dockerfile
This PR removes bitcoin binary from available in Nox
=> chore: removed bitcoin binary from nox

crates/created-swarm/src/swarm.rs, crates/server-config/src/node_config.rs, crates/server-config/src/resolved_config.rs, nox/tests/http_expected_config.toml, nox/tests/http_test_config.toml
Change the case to the lower case for network enum.
=> fix(config): network case

crates/server-config/src/defaults.rs
Change default ports so that they don't overlap with VM networking
=> fix(config)!: change default ws, tcp, http ports

nox/src/main.rs
Check if virtualization is enabled if there's VM configuration in Nox
=> feat(vm): check if virtualization is enabled

crates/chain-listener/src/listener.rs, crates/peer-metrics/src/chain_listener.rs
Count individual proofs in metric
It was counting batches (ie, txs)
Count individual proofs in metric
=> fix(listener,metrics): fix counter of sent proofs
